/* Generated by cbindgen */
#include "lovely_primitives.h"

#ifndef LOVELY_CORE_FFI_H
#define LOVELY_CORE_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define LUA_GLOBALSINDEX -10002

#define LUA_TNIL 0

#define LUA_TBOOLEAN 1

typedef void LuaState;

typedef int32_t (*OriginalLoadbufferx)(LuaState *state,
                                       const uint8_t *buf_ptr,
                                       uintptr_t size,
                                       const uint8_t *name_ptr,
                                       const uint8_t *mode_ptr);

/**
 * 初始化函数，将从 C 调用。
 */
void lovely_init(const char *mod_dir_path, OriginalLoadbufferx original_loader, LuaLib lualib);

/**
 * 这是从 LuaJIT 调用的新入口点。
 * 它的签名精确匹配 luaL_loadbufferx。
 */
int32_t lovely_entrypoint_for_luajit(LuaState *state,
                                     const uint8_t *buf_ptr,
                                     uintptr_t size,
                                     const uint8_t *name_ptr,
                                     const uint8_t *mode_ptr);

#endif  /* LOVELY_CORE_FFI_H */
